<a href="https://colab.research.google.com/github/ss0610/NoLimitCpp/blob/main/Maximization_problem(max_goods_in_truck).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
!git clone https://github.com/gkhayes/mlrose.git
!pip install mlrose/.

Cloning into 'mlrose'...
remote: Enumerating objects: 853, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 853 (delta 245), reused 232 (delta 232), pack-reused 578 (from 1)
Receiving objects: 100% (853/853), 406.85 KiB | 2.86 MiB/s, done.
Resolving deltas: 100% (554/554), done.
Processing ./mlrose
  Preparing metadata (setup.py) ... done
  Created wheel for mlrose: filename=mlrose-1.3.0-py3-none-any.whl size=27705 sha256=7a2bd5f7a338bc36e3f11f5ae8d8e638d784e6fd1109833f9b6aa57842352363
  Stored in directory: /tmp/pip-ephem-wheel-cache-ng90g8lq/wheels/11/a6/5c/ac2f7ff47bd97646e839a8a0dbdf883f7d0c76c69a7580c39b
Successfully built mlrose


In [15]:
import six
import sys
sys.modules['sklearn.externals.six']=six
import mlrose

##Representing the problem

In [17]:
products= [('Refrigerator A',0.751,999.90),
           ('Cell phone',0.0000899,2911.12),
           ('TV 55',0.400,4346.99),
           ('TV 50',0.290,3999.90),
           ('TV 42',0.200,2999.00),
           ('Notebook A',0.00350,2499.90),
           ('Fun',0.496,199.90),
           ('Microwave A',0.0424,308.66),
           ('Microwave B',0.0544,429.90),
           ('Microwave C',0.0319,299.29),
           ('Refrigerator B',0.635,849.89),
           ('Refrigerator C',0.870,1199.90),
           ('Notebook B',0.498,1999.90),
           ('Notebook C',0.527,3999.00)]
avl_space= 3

In [18]:
products[0],products[0][0],products[0][1],products[0][2]

(('Refrigerator A', 0.751, 999.9), 'Refrigerator A', 0.751, 999.9)

In [19]:
def print_sol(solution):
  for i in range(len(solution)):
    if solution[i]==1:
      print('%s - %s'%(products[i][0],products[i][2]))

In [22]:
print_sol([0,1,0,1,0,0,1,0,1,0,1,1,0,1])

Cell phone - 2911.12
TV 50 - 3999.9
Fun - 199.9
Microwave B - 429.9
Refrigerator B - 849.89
Refrigerator C - 1199.9
Notebook C - 3999.0


In [20]:
def fitness_func(solution):
  cost=0
  sum_of_space=0
  for i in range(len(solution)):
    if solution[i]==1:
      sum_of_space+=products[i][1]
      cost+=products[i][2]
  if sum_of_space>avl_space:
    cost=1
  return cost

In [21]:
fitness_func([0,1,0,1,0,0,1,0,1,0,1,1,0,1])

13589.609999999999

In [23]:
fitness=mlrose.CustomFitness(fitness_func)

In [24]:
problem=mlrose.DiscreteOpt(length=14,fitness_fn=fitness,maximize=True,max_val=2)

###Hill Climb

In [25]:
best_solution,best_cost=mlrose.hill_climb(problem,random_state=1)
best_solution,best_cost

(array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]), 15846.57)

In [26]:
print_sol(best_solution)

Refrigerator A - 999.9
Cell phone - 2911.12
TV 42 - 2999.0
Notebook A - 2499.9
Fun - 199.9
Microwave A - 308.66
Microwave B - 429.9
Microwave C - 299.29
Refrigerator C - 1199.9
Notebook C - 3999.0


###Simulated Annealing

In [27]:
best_solution,best_cost=mlrose.simulated_annealing(problem,max_attempts=10,random_state=0)
best_solution,best_cost

/usr/local/lib/python3.11/dist-packages/mlrose/algorithms.py:311: RuntimeWarning: overflow encountered in exp
  prob = np.exp(delta_e/temp)


(array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]), 23643.550000000003)

In [28]:
print_sol(best_solution)

Refrigerator A - 999.9
Cell phone - 2911.12
TV 55 - 4346.99
TV 50 - 3999.9
TV 42 - 2999.0
Notebook A - 2499.9
Microwave A - 308.66
Microwave B - 429.9
Microwave C - 299.29
Refrigerator B - 849.89
Notebook C - 3999.0


###Genetic Algorithm

In [29]:
best_solution,best_cost=mlrose.genetic_alg(problem,pop_size=500,mutation_prob=0.2,random_state=1)
best_solution,best_cost

(array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1]), 24993.560000000005)

In [30]:
print_sol(best_solution)

Cell phone - 2911.12
TV 55 - 4346.99
TV 50 - 3999.9
TV 42 - 2999.0
Notebook A - 2499.9
Microwave A - 308.66
Microwave B - 429.9
Microwave C - 299.29
Refrigerator C - 1199.9
Notebook B - 1999.9
Notebook C - 3999.0
